name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.csproj'

env:
  DOTNET_VERSION: '3.1' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile -c Release -f netcoreapp3.1 -r win-x64
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Application_Artifact
        path: D:\a\HSL\HSL\HSL\bin\Release\netcoreapp3.1\win-x64\publish\
